version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  video-preview:
    lang: python3-http
    build_args:
      ADDITIONAL_PACKAGE: "ffmpeg"
    handler: ./video-preview
    image: badur/video-preview:0.0.3
    environment:
      s3_bucket: video-preview  
      s3_endpoint_url: https://se-sto-1.linodeobjects.com
      write_timeout: 10m2s
      read_timeout: 10m2s
      exec_timeout: 10m
      debug: "true"
    secrets:
      - video-preview-s3-key
      - video-preview-s3-secret

